require('pack')
require('options')
require('mappings')

require('plugins/nerdtree')
require('plugins/fzf')
require('plugins/nerdcommenter')
-- require('plugins/telescope')
require('plugins/git')
require('plugins/treesitter')
require('plugins/lspconfig')
require('plugins/vue')
require('plugins/autocmd')
require('plugins/compe')
require('plugins/toggleterm')
require('plugins/lightline')
require('plugins/autopairs')
