require('pack')
require('options')
require('mappings')

require('plugins/common')
-- require('plugins/nerdtree')
require('plugins/nvim-tree')
require('plugins/fzf')
require('plugins/nerdcommenter')
require('plugins/telescope')
require('plugins/git')
require('plugins/treesitter')
require('plugins/lspconfig')
require('plugins/vue')
require('plugins/autocmd')
require('plugins/compe')
-- require('plugins/lightline')
require('plugins/lualine')
require('plugins/autopairs')
require('plugins/ale')
require('plugins/go')
